### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by YellowZaki** [MassiveCraft/MassiveLight#1]
Hello, I have seen that is the only plugin that relights chunks for 1.8. But unfortunately lot of users (including me) don't know how to compile the plugin so I would like to get the plugin (.jar).
I think that it would be very successful if you post this plugin in bukkit/spigot webpage.
Thanks in advance.

**Comment by markhughes** [comment]
Hello.

I've compiled MassiveLight for you. I think others might find it helpful too. 

To compile these, you have to reference Craftbukkit Server when compiling. 

**MassiveLight for 1.8** @ f9de77264a9fa01980c948dd5afb637d2caf84bd- Download: [MassiveLight_1.8.jar.zip](https://github.com/MassiveCraft/MassiveLight/files/157953/MassiveLight_1.8.jar.zip)
Use [MassiveCore 2.8.6](http://dev.bukkit.org/bukkit-plugins/mcore/files/49-2-8-6/) 

**MassiveLight for 1.9** @ 76399241675f4e9cf43c6627f311f57ac70b5108- Download: [MassiveLight_1.9.jar.zip](https://github.com/MassiveCraft/MassiveLight/files/157955/MassiveLight_1.9.jar.zip)
Use [MassiveCore 2.8.7](http://dev.bukkit.org/bukkit-plugins/mcore/files/51-2-8-7beta-supports-1-9/) 

If you're reading this ticket a few weeks later please [go here](http://dev.bukkit.org/bukkit-plugins/mcore/files/) for the latest MassiveCore.

**Comment by ulumulu1510** [comment]
As markehme said, MassiveLight is NMS  dependant and will break with every minecraft update. This is why we do not want to have it publicly available for the masses.

**Comment by goosewoman** [comment]
Is it possible for you guys to add releases to github or to have a ci server or something? (or use maven so I can set one up for myself!) I'm having a lot of trouble getting this plugin to compile and actually function. (I got it to compile but then the commands didn't work.)

**Comment by markhughes** [comment]
Hey @kukelekuuk00 this isn't really a supported plugin. You require MassiveCore too, have you got MassiveCore?

**Comment by goosewoman** [comment]
Yeah, I do. But it's not working. Guess I'll have to figure something else out.

**Comment by markhughes** [comment]
If you provided us with some more information we might be able to help you a little more 😄  but you've told us nothing? Whats the issue?

**Comment by goosewoman** [comment]
I downloaded the latest version of MassiveCore from spigot. Used that to build the project, loaded it up on my 1.10.2 server. And when I tried to use the command it told me that the command didn't exist. It wasn't in the plugin.yml, so I added it. But now it just doesn't show a message either.

Anyway. I won't be using MassiveLight any more, anyway. I used it because it was easily available, but since it's not really supported any more I'll write my own light fixing plugin. It'll be easier to update.

**Comment by markhughes** [comment]
Great to hear you've come to a solution, good luck! 😃

**Comment by ulumulu1510** [comment]
I just want to update @kukelekuuk00 on this, but we just made MassiveLight multiple version friendly. It can now support 1.10 and 1.11 as of now and we will update it to newer versions without loosing backwards compatibility till 1.10 :)
